### PR TITLE
[JENKINS-51982] Do not create install URL

### PR DESCRIPTION
**Pull request by mezpahlan**
If public_url not available typically because we are using an API key
that has insufficient permissions to create releases. In this scenario `installUrl` resolves to `null/app_versions/{buildId}` which makes no sense to be creating.

@jenkinsci/code-reviewers would you do the honours, please. Thanks.

### CODE REVIEW

**Comment by daniel-beck** [comment]
I don't understand the problem domain well enough to comment (and I expect I'm not the only one in the group). Perhaps an automated test would help?

**Comment by mezpahlan** [comment]
Hi *@daniel-beck*  I'm a new maintainer so wanted to start slowly. An extra
pair of eyes will be the case for a lot of these PRs*. *

Thanks for the comments the suggestion of some automated tests is exactly
the thing I'm looking fo in these reviews.

Cheers.

**Comment by daniel-beck** [comment]
https://github.com/jenkinsci-cert/github-plugin/commit/ce7f5f2cb523757f2bf9ec362e1c8de1de447ec7

**Comment by daniel-beck** [comment]
@mezpahlan Oops, sorry about the accidental closing, got my browser tabs confused.

**Pull request merged**
