### PR TITLE
Allow non-default OldVersionHolder in a Jenkins pipeline

### PR DESCRIPTION
**Pull request by SimonStJG**
I've attempted to fix an issue where it wasn't possible to specify a non-default OldVersionHolder in a Jenkins pipeline job.

To be completely honest, I didn't know anything about writing Jenkins plugins before this, so I've probably not done this correctly, in which case please let me know and I'll try and sort it out.

Cheers,
Simon

### CODE REVIEW

**Comment by Brantone** [comment]
Looking for others to code review. Would like some other eye-balls on this as it's shuffling things up quite a bit.
Sadly there no initial unit tests for this plugin, otherwise would make it easier to add some. Feeling confident enough to take a crack at it?

**Comment by SimonStJG** [comment]
Mm yeah, I can have a go at adding some tests, see how it goes.  Will let you know how I get on either way (success, or failure).

**Comment by SimonStJG** [comment]
Turns out that when I did this PR originally, I didn't appreciate that you had to use a fully qualified class name when using $class with a nested class - hence this PR is invalid and I am closing it.

I did write some tests though, before I figured that out, which I will raise as a separate PR now.

**Comment by ynedelin** [comment]
Hi does this version have an ability to remove old version from hockey app using pipeline jenkins file ?

**Pull request closed without merging**
