### PR TITLE
Add support for Credentials plugin

### PR DESCRIPTION
**Pull request by mezpahlan**
Attempt to add support for Credentials handling as the old method stored credentials in plain text.

Note: This plugin is to be deprecated soon as the HockeyApp service is going to be closed at the end of the year. So I don't particularly mind if the implementation could be better. The whole plugin is going to be re-written anyway. 

I have attempted to provide a migration mechanism for free style jobs so *am* interested if that implementation works. I haven't found a way to do that for Pipeline jobs so will list some instructions on the release page after merging this.

### CODE REVIEW

**Comment by mezpahlan** [comment]
Hi @daniel-beck this is the patch for SECURITY-839 that I didn't get time to do in March. Would you mind giving it a quick review? Also @jenkinsci/code-reviewers if anyone has time.

Just some notes on this, I am looking to deprecate this plugin as the backend service (HockeyApp) is coming to its end of life so I am primarily concerned about keeping existing users happy and not breaking anything for them (or breaking as little as possible) rather than a bigger code clean up.

**Comment by daniel-beck** [comment]
@mezpahlan If you just want to fix the security issue we published as easily as possible, I recommend switching the type of the access token field from `String` to `Secret` (and adapt everything that touches it), see https://javadoc.jenkins.io/hudson/util/Secret.html

Nothing wrong with migrating to credentials, of course. If you still want to proceed with credentials integration, please respond and I'll give this PR a closer look.

**Comment by mezpahlan** [comment]
Now I feel stupid :sob:. 

@daniel-beck Let me see how it would look like to simply migrate the `String` token to `Secret` and I'll then update if I want this PR to continue.

**Comment by mezpahlan** [comment]
Closed in favour of #60

**Pull request closed without merging**
