### PR TITLE
make HockeyApp-plugin compatible with Pipeline

### PR DESCRIPTION
**Pull request by 62mkv**
This PR is a fix of https://github.com/jenkinsci/hockeyapp-plugin/pull/31

### CODE REVIEW

**Comment by Brantone** [comment]
Same as for #31 : throw in a unit test or 2?

**Comment by beazlr02** [comment]
Im interested in helping with this. @Brantone would you be able to give some guidance, there currently exists no (unit) tests at all.

What would be acceptable to you? Extract new additions as method objects and assert they do what we expect or are we talking a major re-architecure to decouple key parts of the system and thus confirm unit functionality?

please help

**Comment by Brantone** [comment]
I'd say even just a couple minor tests to cover the basics ... naturally since it involves a 3rd party, doing integration tests is harder, so starting off with something simple, ex: release notes.

**Comment by 62mkv** [comment]
@Brantone can you pls clarify a little bit. What do you mean by "tests for release notes" ? Can you pls give an example, how was it done in other PRs ? I am totally new to this stuff..

**Comment by Brantone** [comment]
@62mkv I was hoping for something like a unit test for the createReleaseNotes function, or similar.

**Comment by 62mkv** [comment]
@Brantone is this something that's (mostly) relevant to Pipeline compatibility ? I've been through [DEVGUIDE](https://github.com/jenkinsci/pipeline-plugin/blob/master/DEVGUIDE.md) and have not seen anything Pipeline-specific about "release notes"

or is it (one of the) tests, that are broken because of changes in this PR ? just want to understand the context.

**Comment by beazlr02** [comment]
@62mkv im guessing @Brantone has taken over ownership of this component and wants to try and drag it into shape with some automated testing. 

I @Brantone is suggesting that the function createReleaseNotes if big enough to have its behaviours specified in a unit test. It probably makes more sense to move this method to its own object HockeyAppReleaseNotes or some such and have a addToEntity method maybe

e.g.

class HockeyAppReleaseNotes {
 public void addToEntity(MultipartEntity entity)
}

**Comment by 62mkv** [comment]
I am of course no one to have an opinion about this, but.. if I understood it correctly, the current "stable" HockeyApp plugin also does not have these tests, so the proposed PR definitely does not make things worse in this respect. As an average Jenkins+Pipeline user, I would vote for merging this, because it has real added benefit for a whole group of users. In the meantime, someone might probably be interested in writing unit tests for these, but for the moment, I don't see a point in having this functionality blocked by the missing unit-tests, that are not available with a current version anyway!

just saying :)

**Comment by 62mkv** [comment]
also I have to admit that we're currenlty using this PR version of the plugin in our deployment, and have experienced zero problems so far

**Comment by beazlr02** [comment]
All valid points.

I should shut up now anyway as i am speaking on @Brantone s behalf :)

**Comment by almozavr** [comment]
@62mkv which version of Jenkins do you use? I've built and installed plugin, but still see `no known implementation of interface jenkins.tasks.SimpleBuildStep is named HockeyappRecorder`

**Comment by 62mkv** [comment]
@almozavr I use it with Jenkins 2.7.4. I was using this modified plugin with Pipeline via a "Step" option in Pipeline (because it is not otherwise available in Snippet Generator). I guess some modification is still necessary, but this is already functioning solution, which we currently use quite intensively.

**Comment by almozavr** [comment]
@62mkv thanks! I'm on 2.19.1 using
```
step([$class   : 'HockeyappRecorder', applications:
            [[filePath          : apkPath,
              downloadAllowed   : true,
              mandatory         : false,
              notifyTeam        : true,
              teams             : buildParams.hockeyAppTeams.join(','),
              releaseNotesMethod: [$class: 'ChangelogReleaseNotes'],
              uploadMethod      : [$class: 'VersionCreation', appId: buildParams.hockeyAppId]
             ]],
            debugMode: false, failGracefully: true
      ])
```
But still seeing the same error. By "Step" option do you mean exactly the same?

**Comment by almozavr** [comment]
@62mkv I've managed to set it up -> I've built a plugin agains diff `parent` version
```
<parent>
    <groupId>org.jenkins-ci.plugins</groupId>
    <artifactId>plugin</artifactId>
    <version>1.609.2</version>
</parent>
```

**Comment by almozavr** [comment]
It's a bit offtopic, but in terms of pipeline, is there any way to get resulting upload link? E.g. to pass it to jira or smth

**Comment by astuetz** [comment]
@Brantone any plans if/when this can be merged?

**Comment by darraghs** [comment]
Any idea when there will be a new release for this?

**Comment by Brantone** [comment]
All,
Many apologies, transitioned gigs recently which means access to an instance of HockeyApp to fully test everything.
If everyone is in agreement that this is good 'n ready, then I will go ahead and commit the merge.

**Comment by Brantone** [comment]
@62mkv Possible to squash commits down to single?

**Comment by 62mkv** [comment]
@Brantone done

**Comment by AnneTheAgile** [comment]
@almozavr see my PR https://github.com/jenkinsci/hockeyapp-plugin/pull/43

**Pull request merged**
