### PR TITLE
Add support for uploading multiple builds to the same version

### PR DESCRIPTION
**Pull request by Azhrei251**
This PR allows users to specify a version number to upload their builds to. This allows for more than one build to be referenced to the same version. 

The issue initially faced was uploading a new version every build was quickly getting out of hand, and finding specific historic builds (those released to the public) in the app was becoming difficult. Uploading several builds to the same version cuts down on the number of internal versions being shown in-app.

### CODE REVIEW

**Comment by mezpahlan** [comment]
Hi @Azhrei251 thanks for this pull request. Can you do a few things for me please. Could you add in a little description of the problem this solves? I can have a guess by looking at the code but I don't want to make assumptions about it. You should be able to edit the description in PR.

Secondly the PR has merge conflicts that will need to be resolved you can do this by updating your feature branch with the latest from the master branch in the upstream repository.

Thirdly are there any tests that you could add for this? I don't really use HokeyApp like this but instead upload a single build to a pre-existing project so I want to have some more confidence in the form of a unit test.

And finally, I'm sure you've noticed but, the class `HockeyappRecorder` is becoming a bit of a mega class and I don't want to add anything unnecessary to it. Could you break out the enum and the inner class into separate files please. Actually regarding the HTTP verb enum, I'd be surprised if there isn't something existing in the Apache HTTP library that we depend on.

I do appreciate that the rest of the plugin code base isn't like this but I'd like to refactor it in the future so that it is easier to work with so need to start laying down some standards in the interim.

Anyways, thanks for the help!

**Comment by Azhrei251** [comment]
Hey @mezpahlan, thanks for the response. For your comments:

1. Added a description to the PR.
2. Merge conflicts resolved. The wonders of whitespace.
3. I've added a unit test for the version upload case, I hope that helps.
4. Moved HttpInfo to a separate file, removed the enum and used HttpPost/HttpPut.METHOD_NAME constants instead.

Let me know if there's anything else.

Thanks!

**Comment by Azhrei251** [comment]
I've added an overload constructor as recommended

**Comment by MikolajKakol** [comment]
Hi, unfortunately this PR is not backward compatible. Now I'm getting:
```
java.lang.IllegalArgumentException: Arguments to class net.hockeyapp.jenkins.uploadMethod.VersionCreation have to be explicitly named
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:277)
	at org.jenkinsci.plugins.structs.describable.UninstantiatedDescribable.instantiate(UninstantiatedDescribable.java:168)
```
My current configuration was:
`                        uploadMethod: versionCreation('xxx')`
now as I understand I need to pass versionCode. Which is pain, because I don't have access to that in Jenkinsfile.

**Comment by MikolajKakol** [comment]
I have no idea how jenkins plugins works but I think that old constructor shouldn't be deprecated and it still should have this `    @DataBoundConstructor` annotation.

**Comment by mezpahlan** [comment]
Hi @MikolajKakol I've [created a bug in the issue tracker](https://issues.jenkins-ci.org/browse/JENKINS-54498). Let's continue the discussion over there for now until we can create another PR. Thanks.

**Pull request merged**
