### PR TITLE
[Jenkins-54498] version creation databoundconstructor regression

### PR DESCRIPTION
**Pull request by mezpahlan**
Carried over from regression in #52. Attempting to make the `versionCreation` field optional by making better use of `@DataBoundSetter` functionality.

### CODE REVIEW

**Comment by mezpahlan** [comment]
Hi @@MikolajKakol are you able to test these changes out? Hopefully it fixes the issue you were having.

**Comment by mezpahlan** [comment]
@jenkinsci/code-reviewers Could you also give this a look. The original problem was that we introduced a new parameter in the `@DataBoundContructor` that forced a new behaviour on existing users that really should have been optional. I think now we fall back to a sensible default if no additional parameter is explicitly set in the pipeline..... At least that's what I hope :smile_cat:

**Comment by MikolajKakol** [comment]
I tested `1.4.0-SNAPSHOT (private-d9c692c6-jenkins)`  from https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fhockeyapp-plugin/detail/PR-56/2/artifacts
and it worked. Thx!

**Comment by mezpahlan** [comment]
@MikolajKakol Thank you for confirming. I'll wait until the Jenkins Code Reviewers have a look before merging.

**Comment by mezpahlan** [comment]
I've added some tests for this confirming the new behavioural changes and hopefully should protect against further breakages. 

@jenkinsci/code-reviewers If one of you has time I'd appreciate a quick look over this. The original problem was that we introduced a new parameter in the @DataBoundContructor that forced a new behaviour on existing users that really should have been optional. I think now we fall back to a sensible default if no additional parameter is explicitly set in the pipeline.

**Pull request merged**
